####################################
# Automatically generated by SMake #
# https://github.com/kala13x/smake #
####################################

CXXFLAGS = -Wall -g -O2
CXXFLAGS += -I./src
LIBS = 
NAME = libxpack.a
ODIR = obj
OBJ = o

OBJS = packetizer.$(OBJ)
OBJECTS = $(patsubst %,$(ODIR)/%,$(OBJS))
VPATH = ./src

.cpp.$(OBJ):
	@test -d $(ODIR) || mkdir -p $(ODIR)
	$(CXX) $(CXXFLAGS) -c -o $(ODIR)/$@ $< $(LIBS)

$(NAME):$(OBJS)
	$(AR) rcs -o $(ODIR)/$(NAME) $(OBJECTS)

.PHONY: clean
clean:
	$(RM) $(ODIR)/$(NAME) $(OBJECTS)
